### ISSUE TITLE
Docker compose file?

### ISSUE THREAD

**Issue by killmasta93** [iwayvietnam/zimbra-docker#7]
Hi
Was looking at the repo, wanted to thank you for the time you took to create it, Im going to test it out but i have a few question,
1) is there a docker compose file?
2) does this come with letsencrypt?
3) is the volume able to mount on another location?
4) how often is this repo updated?

Thank you

**Comment by tuanta** [comment]
> Hi Was looking at the repo, wanted to thank you for the time you took to create it, Im going to test it out but i have a few question,
> 
> 1. is there a docker compose file?
Yes, it is in docker-compose folder. It may be a bit out-dated but you can still take it and modify what you want.

> 2. does this come with letsencrypt?
Not yet. You can install it later.

> 3. is the volume able to mount on another location?
Yes, any types of Docker volume.

> 4. how often is this repo updated?
I have not updated it for a while since I have not much time these days.
However, if you see it is useful with you you are welcome to fork/contribute to the project.
If you are not a techie, you can also file an issue and I am happy to do it on my free time.

**Comment by killmasta93** [comment]
Hi there, Thank you so much will give a try and post back thank you again
